### ISSUE TITLE
Missing some types on event manager

### ISSUE THREAD

**Issue by csandman** [seatsio/seatsio-types#11]
Hey folks at seatsio, I've recently started using the `<SeatsioEventManager>` component from your `@seatsio/seatsio-react` package, and I noticed that a few of the types that are in your documentation are not included in the types. I am specifically using the event manager in `select` mode, so I am specifically talking about the [`EventManagerSelectModeConfigOptions`](https://github.com/seatsio/seatsio-types/blob/f592f1f0b87eb4de59d5c1087a3fd1ec5495152b/src/index.ts#L384-L394) type.

First, the `objectIcon` object override function: https://docs.seats.io/docs/event-manager/modes/select#objecticon

As shown in the docs, this should be available on the event manager in select mode, but the type is missing from it.

<img width="692" alt="image" src="https://github.com/seatsio/seatsio-types/assets/9214195/998b6a8d-9842-4b26-9450-bfa0ba4d5f4a">

```
Type '{ colors?: { colorSelected?: string | undefined; cursorTooltipBackgroundColor?: string | undefined; colorTitle?: string | undefined; availableObjectColor?: string | undefined; selectedObjectColor?: string | undefined; errorColor?: string | undefined; } | undefined; ... 38 more ...; objectIcon: (object: SelectableObj...' is not assignable to type 'IntrinsicAttributes & (IntrinsicClassAttributes<SeatsioEventManager> & ((Pick<Readonly<{ onRenderStarted?: ((chart: EventManager | SeatingChart) => void) | undefined; chartJsUrl?: string | undefined; region: Region; } & EventManagerSelectModeConfigOptions>, "region" | ... 1 more ... | "onRenderStarted"> & InexactPar...'.
  Property 'objectIcon' does not exist on type '(IntrinsicAttributes & IntrinsicClassAttributes<SeatsioEventManager> & Pick<Readonly<{ onRenderStarted?: ((chart: EventManager | SeatingChart) => void) | undefined; chartJsUrl?: string | undefined; region: Region; } & EventManagerSelectModeConfigOptions>, "region" | ... 1 more ... | "onRenderStarted"> & InexactParti...'.
```

---

Second is the `chart.selectedObjects` value on the `EventManager` object: https://docs.seats.io/docs/event-manager/modes/select#retrieving-the-selected-objects

This is also supposedly available on the chart object (I am getting it out of the `onChartRendered` function), but it is not. 

<img width="784" alt="image" src="https://github.com/seatsio/seatsio-types/assets/9214195/f85f1066-05a2-460b-a0dc-2078f212ef11">

```
Property 'selectedObjects' does not exist on type 'EventManager'. Did you mean 'selectObjects'?
```

I am still able to get the selected object using `await chart.listSelectedObjects()`, but this makes my code a decent amount more complicated.

---

It would be great if these types could be updated! I know `objectIcon` works, as I'm currently using that in my code, but I hadn't actually tried the `selectedObjects` one, as there is an alternative. If that's not actually supposed to work, it would be great if you could update the docs.

**Comment by csandman** [comment]
Awesome, thanks for the fast turnaround!

**Comment by mroloux** [comment]
Yes, that's done in [v14.](https://github.com/seatsio/seatsio-react/releases/tag/v14.13.0)
