### ISSUE TITLE
trySelectObjects type does not accurately reflect the implementation

### ISSUE THREAD

**Issue by trodrigues** [seatsio/seatsio-types#29]
The type for [trySelectObjects](https://github.com/seatsio/seatsio-types/blob/e7d26f737fed747dd29c5e7b1de32b0a23a144e9/src/index.ts#L1443) does not seem to accurately reflect the implementation which looks like the following (from actually debugging through the code and seeing the code running in production):

```
seatsio.SeatingChart.prototype.trySelectObjects = function (objectUuidsOrLabels, successCallback, errorCallback) {
    return this.asyncRequestAfterSeatsioLoaded({
        type: 'trySelectObjects',
        objectUuidsOrLabels
    }, successCallback, errorCallback)
}
```

At the same time, when calling this function and producing an error, for example trying to select an object that a different user might've selected at the same time, the callback that fires is the successCallback and not the errorCallback, even though I can see and error being produced in the browser console:

```
SeatsioError: Ignoring selection of 302-DD-6
    at pA.selectionIgnored (chartRenderer.df49e13a.js:16:62783)
    at pS.confirmSelect (chartRenderer.df49e13a.js:22:44803)
    at chartRenderer.df49e13a.js:56:121310
    at chartRenderer.df49e13a.js:56:121524
    at Array.forEach (<anonymous>)
    at vE.selectObjects (chartRenderer.df49e13a.js:56:121513)
    at vE.trySelectObjects (chartRenderer.df49e13a.js:56:120373)
    at yM.trySelectObjects (chartRenderer.df49e13a.js:68:29585)
    at chartRenderer.df49e13a.js:82:45991
```

**Comment by mroloux** [comment]
Hi,

What exactly do you mean by `does not seem to accurately reflect the implementation`?

The `successCallback` and `errorCallback` parameters are deprecated, that's why we don't mention them in `seatsio-types`.

**Comment by trodrigues** [comment]
I see. Then perhaps it would be a good update to also update the documentation [here](https://docs.seats.io/docs/renderer/chart-properties-charttryselectobjects) as it still shows the callback pattern rather than the promise pattern.

The other issue is that even when using the promise pattern, it never seems to trigger an error when trying to select a seat that was already selected.

In our integration we have a usage pattern where we'll sometimes try to reselect a seat a user might've previously selected, so we'll do it programmatically by using this call.

For example, I had two different user sessions on different browsers:
- On the first browser I selected a specific seat, let's say E16
- On that first browser I then change to another seat, for example E15
- On the second browser I select E15
- If I try to select E16 again on the first browser via `trySelectObjects`, I see an error in the console but the promise still resolves instead of rejecting.

I can still detect this situation by looking at the `selectedObjects` property in the chart after the call which seems to reflect the current seat selection accurately, but it's a bit confusing to have a call named `trySelectObjects` that should return an error when that selection fails and it doesn't seem to do so.

**Comment by mroloux** [comment]
Good point: we've updated our docs.

And yes, the promise returned by `trySelectObjects` should get reject in case of errors. We'll look into that.

**Comment by trodrigues** [comment]
Unfortunately not in a way that's very easy to share.

I've tried both of these ways:
```
      chart.trySelectObjects(["303-EE-15"]).catch((err) => {
        debugger;
      });
```

```
      try {
        await chart.trySelectObjects(["303-EE-15"]);
      } catch (error) {
        debugger;
      }
```

In both of these situations I couldn't get the breakpoint to stop there.

However, if I do check `chart.selectedObjects` after that call, it will be reflected accurately (for example, in this situation it would be 0).

**Comment by mroloux** [comment]
This seems to work fine for me:

https://jsfiddle.net/73xcs90u/

**Comment by trodrigues** [comment]
I think the issue only reflects itself when it's two different users on two completely separate browser sessions, and this doesn't seem to be possible with this public demo chart.

If I open that fiddle in two different browsers and select the same seats, I don't see the seats becoming unavailable in the other browser in realtime.

That will happen if I do that for example in our implementation here: https://www.getyourguide.com/las-vegas-l58/las-vegas-o-by-cirque-du-soleil-at-bellagio-t398243?date_from=2024-12-27&_pc=1,2

**Comment by mroloux** [comment]
Are you calling `trySelectObjects` on that page? Normally there's no need to do that, if you let the ticket buyer pick seats on the chart.

**Comment by trodrigues** [comment]
Yes, we are doing it on a certain edge case.

Because we have this concept of "confirming" the seats first, in a situation where the customer might confirm theirs seats and then open the modal again, if they select different seats without confirming we don't want them to accidentally change seats without taking that explicit action.

As such, if they pick new seats and close the modal (via the X icon or clicking on the background) without confirming the new seats, we use `trySelectObjects` to reselect the seats they had previously confirmed.

But in the case where those seats might've been booked by someone else in the meanwhile we want to detect that error and clear the selection entirely so they don't try to book something that might be gone.

**Comment by trodrigues** [comment]
> Are you passing in numberOfPlacesToSelect to the seating chart?

Yes, exactly.

For now we don't have ticket type selection but we might incorporate that soon as we integrate our different pricing categories so we'll keep that in mind. Thanks for the tip!

**Comment by mroloux** [comment]
`trySelectObjects` now properly rejects when the selection fails and you're using `numberOfPlacesToSelect`. Thanks for reporting htis!

**Comment by trodrigues** [comment]
Nice! Thanks for following up and fixing the issue.
