### ISSUE TITLE
`SelectableObjectProps` missing some keys

### ISSUE THREAD

**Issue by csandman** [seatsio/seatsio-types#9]
Hey folks at Seats.io. I am currently using your React renderer, and I've been getting into some custom object colors/icons. I notice the description for the `objectColor` getter function states the following:

> ## `objectColor`
> Type: `function(object, defaultColor, extraConfig)`
> 
> By default, color will be grey if the object is not available for selection, or the category color otherwise.
> 
> A function that determines the object color. Can be based on `object.status`, `object.category`, `object.selectable` or on other criteria.

The field I'd like to use in my case is `object.status`, however the `SelectableObjectProps` interface does not include it. I do however see the `status` field in the object if I console log inside the `objectColor` function. I'm not sure if in this case, the `status` field is missing from `SelectableObjectProps`, or if the function argument should be something different like `BookableObjectProps`, which does include the `status` field. Or even something like `(object: SelectableObjectProps | BookableObjectProps)`.

If you do change the function argument though, we also need this field in the `objectIcon` and `objectLabel` getter typing as well, so it would be great if it could be updated for them all.

**Comment by csandman** [comment]
Actually, I was able to get the correct type by first using the `isSeat` type guard function you have exported from the react package. Is doing that the intended behavior?

**Comment by csandman** [comment]
> The function signature is actually correct: some of our customers let their users select sections instead of specific seats. In that case, `objectColor` (and the other callbacks) receive a `SelectableObjectProps` object that does not comply with `BookableObjectProps`.

In that case, it would still make more sense to to provide the function with a union of all of the possible types for `object`, instead of just providing the minimum overlap (`(object: SelectableObjectProps | BookableObjectProps)`). If done that way, users still have to check for existence of the attributes that are specific to one of the arguments in order to narrow the type of the argument. Something like this:

```ts
export const getObjectColor = (
  object: SelectableObjectProps | BookableObjectProps,
  defaultColor: string,
): string => {
  // This casting shouldn't be necessary, but the type definitions are wrong.
  // https://github.com/seatsio/seatsio-types/issues/9
  if ('status' in object && object.status === 'MY_CUSTOM_STATUS') {
    if (object.selectable) {
      return '#365DEA';
    }
  }

  return defaultColor;
};
```

Realistically, the `SelectableObjectProps` type itself would be better off as a union of the potentially selectable object types, instead of just the always available props. That would prevent the need for type assertions (which are generally not a recommended approach if avoidable), and could be narrowed natively using built-in typescript functionality.

For example, I know you guys have [these type guard functions in your react package](https://github.com/seatsio/seatsio-react/blob/master/src/main/util.ts#L22-L26):

```ts
export const isSeat = (obj: SelectableObjectProps): obj is SeatProps => obj.objectType === 'Seat'
export const isTable = (obj: SelectableObjectProps): obj is TableProps => obj.objectType === 'Table'
export const isSection = (obj: SelectableObjectProps): obj is InteractiveSectionProps => obj.objectType === 'section'
export const isBooth = (obj: SelectableObjectProps): obj is BoothProps => obj.objectType === 'Booth'
export const isGeneralAdmission = (obj: SelectableObjectProps): obj is GeneralAdmissionAreaProps => obj.objectType === 'GeneralAdmissionArea'
```

These shouldn't even be necessary if you typed each of these objects with fixed string props for their `objectType`.

---

Say for example, you used these interfaces instead;

```ts
export interface SeatProps extends BookableObjectProps {
  readonly objectType: 'Seat'
  readonly center: { x: number; y: number }
  readonly isOrphan: boolean
  readonly viewFromSeatUrl?: string
  readonly parent: { type: 'row' | 'table' }

  pulse: () => Promise<void>
  unpulse: () => Promise<void>
}

export interface TableProps extends BookableObjectProps {
	readonly objectType: 'Table'
    readonly seats: NonBookableTableSeatProps[]
    readonly center: { x: number; y: number }
}

// ...etc...

export type SelectableObject = SeatProps | TableProps // ...etc...
```

Given the fixed value for `objectType`, you wouldn't even have to use a type guard to determine the type of the object props, as they'd already be easily natively determined using [union discrimination](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#discriminated-unions). You can see in this example, that TS knows just by checking `objectType` what the typing of the object is:

![image](https://github.com/seatsio/seatsio-types/assets/9214195/71c4547d-cebb-43d7-a61c-42173ce71354)

---

I know your packages already do something very similar to this with your [`EventManagerConfigOptions`](https://github.com/seatsio/seatsio-types/blob/main/src/index.ts#L362-L410), which narrows the types of the available config options as soon as you pass in the `mode` attribute. It would be great if this approach could be extended to the object types to avoid having to assert types, as that's not a very safe approach to using third party typescript libraries in general.

**Comment by mroloux** [comment]
Thanks for the suggestions, we made some changes to increase type safety in v3.0.0.

**Comment by csandman** [comment]
@mroloux I just checked out the PR and tried the changes locally, and they work great! I was able to remove all of my casting, and everything is still working properly.

Thanks a lot for taking my recommendation into consideration!

**Comment by csandman** [comment]
Also, could you guys update your react package to use the newest types?
